### ISSUE TITLE
Test suite errors do not show up on the HTML reports

### ISSUE THREAD

**Issue by djangofan** [afranken/jmeter-analysis-maven-plugin#31]
Test suite errors do not show up on the HTML reports.
What I see instead is that when an error occurs, it seems to leave that request out of the report and so it doesn't show up on the report at all.    On a test suite with 50% errors, I only see 50% of the requests on the report and they are all the successful ones.

NOTE: If I am not understanding something, does anyone know why i might experience something like this? There doesn't seem to be a jmeter property that controls showing errors or not and so I have no idea why errors are being filtered out.

**Comment by afranken** [comment]
how exactly does the jmeter results file look like?
