### ISSUE TITLE
Unable to parse jtl file

### ISSUE THREAD

**Issue by vpk2016** [afranken/jmeter-analysis-maven-plugin#40]
When we run performance tests, and if we have errors on jmeter run or if jtl file is large, we see below error while parsing the jtl file.

[ERROR] Failed to execute goal com.lazerycode.jmeter:jmeter-analysis-maven-plugin:1.0.6:analyze (default) on project jmeter-maven: Error analysing: Character reference "&# -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by afranken** [comment]
do you have an example for a JTL file that produces this error?

**Comment by vpk2016** [comment]
Hi,

PFA of jtl file for your reference.

Thanks,
Kumar

On Tue, May 24, 2016 at 2:04 AM, Arne Franken <notifications@github.com>
wrote:

> do you have an example for a JTL file that produces this error?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/afranken/jmeter-analysis-maven-plugin/issues/40#issuecomment-221087914>
>

​
 IRA.jtl
<https://drive.google.com/file/d/0B89fHD9OVApCcHhwanNpNGNDREE/view?usp=drive_web>
​

**Comment by afranken** [comment]
Hi,
you're persisting all responses of your test into the JTL file, including binary responses (images I guess?). These contain characters that are illegal in a XML file (i.e. `&#x0;`) , so the file can't be parsed.
Cheers,
Arne

**Comment by vpk2016** [comment]
Thanks, it helped. I am able to parse now.
